export type Emoji = {
	/** The emoji character. */
	e: string;
	/** Display name, also searched. */
	n: string;
	/** Extra search keywords, space separated. */
	k?: string;
	/** Supports the five Fitzpatrick skin tone modifiers. */
	t?: true;
};

export type EmojiCategoryId =
	| 'recent'
	| 'smileys'
	| 'people'
	| 'nature'
	| 'food'
	| 'activity'
	| 'travel'
	| 'objects'
	| 'symbols'
	| 'flags';

export type EmojiCategory = {
	id: EmojiCategoryId;
	label: string;
	emojis: Emoji[];
};

export const SKIN_TONES = [
	{ id: 0, label: 'Default', modifier: '', swatch: '✋' },
	{ id: 1, label: 'Light', modifier: '\u{1F3FB}', swatch: '✋\u{1F3FB}' },
	{ id: 2, label: 'Medium light', modifier: '\u{1F3FC}', swatch: '✋\u{1F3FC}' },
	{ id: 3, label: 'Medium', modifier: '\u{1F3FD}', swatch: '✋\u{1F3FD}' },
	{ id: 4, label: 'Medium dark', modifier: '\u{1F3FE}', swatch: '✋\u{1F3FE}' },
	{ id: 5, label: 'Dark', modifier: '\u{1F3FF}', swatch: '✋\u{1F3FF}' }
] as const;

const VARIATION_SELECTOR = '\uFE0F';

/**
 * Applies a Fitzpatrick modifier to an emoji. The modifier goes directly after
 * the base character — before any ZWJ sequence — and replaces a variation
 * selector when one is present (e.g. ✌️ -> ✌🏽).
 */
export function applySkinTone(emoji: Emoji, tone: number): string {
	const modifier = SKIN_TONES[tone]?.modifier;
	if (!emoji.t || !modifier) return emoji.e;

	const codepoints = [...emoji.e];
	const rest = codepoints.slice(1);
	if (rest[0] === VARIATION_SELECTOR) rest.shift();

	return codepoints[0] + modifier + rest.join('');
}

export const emojiCategories: EmojiCategory[] = [
	{
		id: 'smileys',
		label: 'Smileys & Emotion',
		emojis: [
			{ e: '😀', n: 'grinning face', k: 'happy smile' },
			{ e: '😃', n: 'grinning face with big eyes', k: 'happy smile' },
			{ e: '😄', n: 'grinning face with smiling eyes', k: 'happy joy' },
			{ e: '😁', n: 'beaming face with smiling eyes', k: 'grin' },
			{ e: '😆', n: 'grinning squinting face', k: 'laugh haha' },
			{ e: '😅', n: 'grinning face with sweat', k: 'relief phew' },
			{ e: '🤣', n: 'rolling on the floor laughing', k: 'rofl lol' },
			{ e: '😂', n: 'face with tears of joy', k: 'lol cry laugh' },
			{ e: '🙂', n: 'slightly smiling face', k: 'smile' },
			{ e: '🙃', n: 'upside down face', k: 'sarcasm silly' },
			{ e: '🫠', n: 'melting face', k: 'hot heat' },
			{ e: '😉', n: 'winking face', k: 'wink flirt' },
			{ e: '😊', n: 'smiling face with smiling eyes', k: 'blush happy' },
			{ e: '😇', n: 'smiling face with halo', k: 'angel innocent' },
			{ e: '🥰', n: 'smiling face with hearts', k: 'love adore' },
			{ e: '😍', n: 'smiling face with heart eyes', k: 'love crush' },
			{ e: '🤩', n: 'star struck', k: 'starry eyes wow' },
			{ e: '😘', n: 'face blowing a kiss', k: 'kiss love' },
			{ e: '😗', n: 'kissing face', k: 'kiss' },
			{ e: '😚', n: 'kissing face with closed eyes', k: 'kiss' },
			{ e: '😙', n: 'kissing face with smiling eyes', k: 'kiss' },
			{ e: '🥲', n: 'smiling face with tear', k: 'grateful proud' },
			{ e: '😋', n: 'face savoring food', k: 'yum tasty' },
			{ e: '😛', n: 'face with tongue', k: 'tongue silly' },
			{ e: '😜', n: 'winking face with tongue', k: 'crazy silly' },
			{ e: '🤪', n: 'zany face', k: 'goofy wild' },
			{ e: '😝', n: 'squinting face with tongue', k: 'prank' },
			{ e: '🤑', n: 'money mouth face', k: 'rich dollar' },
			{ e: '🤗', n: 'smiling face with open hands', k: 'hug' },
			{ e: '🤭', n: 'face with hand over mouth', k: 'oops giggle' },
			{ e: '🫢', n: 'face with open eyes and hand over mouth', k: 'gasp shock' },
			{ e: '🤫', n: 'shushing face', k: 'quiet secret' },
			{ e: '🤔', n: 'thinking face', k: 'hmm consider' },
			{ e: '🫡', n: 'saluting face', k: 'respect yes sir' },
			{ e: '🤐', n: 'zipper mouth face', k: 'silence secret' },
			{ e: '🤨', n: 'face with raised eyebrow', k: 'suspicious doubt' },
			{ e: '😐', n: 'neutral face', k: 'meh blank' },
			{ e: '😑', n: 'expressionless face', k: 'blank' },
			{ e: '😶', n: 'face without mouth', k: 'speechless' },
			{ e: '🫥', n: 'dotted line face', k: 'invisible hide' },
			{ e: '😏', n: 'smirking face', k: 'smug' },
			{ e: '😒', n: 'unamused face', k: 'annoyed' },
			{ e: '🙄', n: 'face with rolling eyes', k: 'eyeroll' },
			{ e: '😬', n: 'grimacing face', k: 'awkward yikes' },
			{ e: '😮‍💨', n: 'face exhaling', k: 'sigh relief' },
			{ e: '🤥', n: 'lying face', k: 'pinocchio liar' },
			{ e: '😌', n: 'relieved face', k: 'calm content' },
			{ e: '😔', n: 'pensive face', k: 'sad down' },
			{ e: '😪', n: 'sleepy face', k: 'tired' },
			{ e: '🤤', n: 'drooling face', k: 'hungry' },
			{ e: '😴', n: 'sleeping face', k: 'zzz sleep' },
			{ e: '😷', n: 'face with medical mask', k: 'sick mask' },
			{ e: '🤒', n: 'face with thermometer', k: 'sick fever' },
			{ e: '🤕', n: 'face with head bandage', k: 'hurt injured' },
			{ e: '🤢', n: 'nauseated face', k: 'sick gross' },
			{ e: '🤮', n: 'face vomiting', k: 'sick puke' },
			{ e: '🤧', n: 'sneezing face', k: 'sick tissue' },
			{ e: '🥵', n: 'hot face', k: 'heat sweat' },
			{ e: '🥶', n: 'cold face', k: 'freezing' },
			{ e: '🥴', n: 'woozy face', k: 'dizzy drunk' },
			{ e: '😵', n: 'face with crossed out eyes', k: 'dead knocked out' },
			{ e: '🤯', n: 'exploding head', k: 'mind blown wow' },
			{ e: '🤠', n: 'cowboy hat face', k: 'yeehaw' },
			{ e: '🥳', n: 'partying face', k: 'celebrate birthday' },
			{ e: '🥸', n: 'disguised face', k: 'incognito' },
			{ e: '😎', n: 'smiling face with sunglasses', k: 'cool' },
			{ e: '🤓', n: 'nerd face', k: 'geek smart' },
			{ e: '🧐', n: 'face with monocle', k: 'inspect' },
			{ e: '😕', n: 'confused face', k: 'unsure' },
			{ e: '🫤', n: 'face with diagonal mouth', k: 'meh unsure' },
			{ e: '😟', n: 'worried face', k: 'concern' },
			{ e: '🙁', n: 'slightly frowning face', k: 'sad' },
			{ e: '😮', n: 'face with open mouth', k: 'surprise wow' },
			{ e: '😯', n: 'hushed face', k: 'surprise' },
			{ e: '😲', n: 'astonished face', k: 'shocked' },
			{ e: '😳', n: 'flushed face', k: 'embarrassed blush' },
			{ e: '🥺', n: 'pleading face', k: 'puppy eyes beg' },
			{ e: '🥹', n: 'face holding back tears', k: 'proud emotional' },
			{ e: '😦', n: 'frowning face with open mouth', k: 'sad' },
			{ e: '😨', n: 'fearful face', k: 'scared' },
			{ e: '😰', n: 'anxious face with sweat', k: 'nervous' },
			{ e: '😥', n: 'sad but relieved face', k: 'phew' },
			{ e: '😢', n: 'crying face', k: 'sad tear' },
			{ e: '😭', n: 'loudly crying face', k: 'sob bawling' },
			{ e: '😱', n: 'face screaming in fear', k: 'scream shock' },
			{ e: '😖', n: 'confounded face', k: 'frustrated' },
			{ e: '😣', n: 'persevering face', k: 'struggle' },
			{ e: '😞', n: 'disappointed face', k: 'sad' },
			{ e: '😓', n: 'downcast face with sweat', k: 'tired' },
			{ e: '😩', n: 'weary face', k: 'tired done' },
			{ e: '😫', n: 'tired face', k: 'exhausted' },
			{ e: '🥱', n: 'yawning face', k: 'bored sleepy' },
			{ e: '😤', n: 'face with steam from nose', k: 'triumph angry' },
			{ e: '😡', n: 'enraged face', k: 'angry mad' },
			{ e: '😠', n: 'angry face', k: 'mad' },
			{ e: '🤬', n: 'face with symbols on mouth', k: 'swearing cursing' },
			{ e: '😈', n: 'smiling face with horns', k: 'devil mischief' },
			{ e: '👿', n: 'angry face with horns', k: 'devil imp' },
			{ e: '💀', n: 'skull', k: 'dead death' },
			{ e: '☠️', n: 'skull and crossbones', k: 'poison danger' },
			{ e: '💩', n: 'pile of poo', k: 'poop crap' },
			{ e: '🤡', n: 'clown face', k: 'joker' },
			{ e: '👻', n: 'ghost', k: 'boo halloween' },
			{ e: '👽', n: 'alien', k: 'ufo space' },
			{ e: '🤖', n: 'robot', k: 'bot ai' },
			{ e: '😺', n: 'grinning cat', k: 'cat happy' },
			{ e: '😹', n: 'cat with tears of joy', k: 'cat lol' },
			{ e: '😻', n: 'smiling cat with heart eyes', k: 'cat love' },
			{ e: '🙀', n: 'weary cat', k: 'cat shock' },
			{ e: '😿', n: 'crying cat', k: 'cat sad' },
			{ e: '💌', n: 'love letter', k: 'heart mail' },
			{ e: '💘', n: 'heart with arrow', k: 'cupid love' },
			{ e: '💝', n: 'heart with ribbon', k: 'gift love' },
			{ e: '💖', n: 'sparkling heart', k: 'love' },
			{ e: '💗', n: 'growing heart', k: 'love' },
			{ e: '💓', n: 'beating heart', k: 'love pulse' },
			{ e: '💞', n: 'revolving hearts', k: 'love' },
			{ e: '💕', n: 'two hearts', k: 'love' },
			{ e: '❣️', n: 'heart exclamation', k: 'love' },
			{ e: '💔', n: 'broken heart', k: 'breakup sad' },
			{ e: '❤️‍🔥', n: 'heart on fire', k: 'passion love' },
			{ e: '❤️', n: 'red heart', k: 'love' },
			{ e: '🧡', n: 'orange heart', k: 'love' },
			{ e: '💛', n: 'yellow heart', k: 'love' },
			{ e: '💚', n: 'green heart', k: 'love' },
			{ e: '💙', n: 'blue heart', k: 'love' },
			{ e: '💜', n: 'purple heart', k: 'love' },
			{ e: '🖤', n: 'black heart', k: 'love' },
			{ e: '🤍', n: 'white heart', k: 'love' },
			{ e: '🤎', n: 'brown heart', k: 'love' },
			{ e: '💯', n: 'hundred points', k: 'perfect score' },
			{ e: '💢', n: 'anger symbol', k: 'mad' },
			{ e: '💥', n: 'collision', k: 'boom explosion' },
			{ e: '💫', n: 'dizzy', k: 'star' },
			{ e: '💦', n: 'sweat droplets', k: 'water splash' },
			{ e: '💨', n: 'dashing away', k: 'wind fast' },
			{ e: '🕳️', n: 'hole', k: 'empty' },
			{ e: '💬', n: 'speech balloon', k: 'comment chat' },
			{ e: '💭', n: 'thought balloon', k: 'thinking' },
			{ e: '💤', n: 'zzz', k: 'sleep' }
		]
	},
	{
		id: 'people',
		label: 'People & Body',
		emojis: [
			{ e: '👋', n: 'waving hand', k: 'hello bye', t: true },
			{ e: '🤚', n: 'raised back of hand', k: 'stop', t: true },
			{ e: '🖐️', n: 'hand with fingers splayed', k: 'five', t: true },
			{ e: '✋', n: 'raised hand', k: 'stop high five', t: true },
			{ e: '🖖', n: 'vulcan salute', k: 'spock', t: true },
			{ e: '🫱', n: 'rightwards hand', k: 'shake', t: true },
			{ e: '🫲', n: 'leftwards hand', k: 'shake', t: true },
			{ e: '👌', n: 'ok hand', k: 'perfect', t: true },
			{ e: '🤌', n: 'pinched fingers', k: 'italian', t: true },
			{ e: '🤏', n: 'pinching hand', k: 'small tiny', t: true },
			{ e: '✌️', n: 'victory hand', k: 'peace two', t: true },
			{ e: '🤞', n: 'crossed fingers', k: 'luck hope', t: true },
			{ e: '🫰', n: 'hand with index finger and thumb crossed', k: 'money heart', t: true },
			{ e: '🤟', n: 'love you gesture', k: 'ily', t: true },
			{ e: '🤘', n: 'sign of the horns', k: 'rock metal', t: true },
			{ e: '🤙', n: 'call me hand', k: 'shaka hang loose', t: true },
			{ e: '👈', n: 'backhand index pointing left', k: 'point', t: true },
			{ e: '👉', n: 'backhand index pointing right', k: 'point', t: true },
			{ e: '👆', n: 'backhand index pointing up', k: 'point', t: true },
			{ e: '👇', n: 'backhand index pointing down', k: 'point', t: true },
			{ e: '☝️', n: 'index pointing up', k: 'one point', t: true },
			{ e: '🫵', n: 'index pointing at the viewer', k: 'you', t: true },
			{ e: '👍', n: 'thumbs up', k: 'like yes approve', t: true },
			{ e: '👎', n: 'thumbs down', k: 'dislike no', t: true },
			{ e: '✊', n: 'raised fist', k: 'power', t: true },
			{ e: '👊', n: 'oncoming fist', k: 'punch bump', t: true },
			{ e: '🤛', n: 'left facing fist', k: 'bump', t: true },
			{ e: '🤜', n: 'right facing fist', k: 'bump', t: true },
			{ e: '👏', n: 'clapping hands', k: 'applause bravo', t: true },
			{ e: '🙌', n: 'raising hands', k: 'praise celebrate', t: true },
			{ e: '🫶', n: 'heart hands', k: 'love', t: true },
			{ e: '👐', n: 'open hands', k: 'hug', t: true },
			{ e: '🤲', n: 'palms up together', k: 'pray ask', t: true },
			{ e: '🤝', n: 'handshake', k: 'deal agreement' },
			{ e: '🙏', n: 'folded hands', k: 'pray thanks please', t: true },
			{ e: '✍️', n: 'writing hand', k: 'write sign', t: true },
			{ e: '💅', n: 'nail polish', k: 'manicure', t: true },
			{ e: '🤳', n: 'selfie', k: 'photo', t: true },
			{ e: '💪', n: 'flexed biceps', k: 'strong muscle', t: true },
			{ e: '🦾', n: 'mechanical arm', k: 'prosthetic' },
			{ e: '🦿', n: 'mechanical leg', k: 'prosthetic' },
			{ e: '🦵', n: 'leg', k: 'kick', t: true },
			{ e: '🦶', n: 'foot', k: 'stomp', t: true },
			{ e: '👂', n: 'ear', k: 'listen hear', t: true },
			{ e: '👃', n: 'nose', k: 'smell', t: true },
			{ e: '🧠', n: 'brain', k: 'smart mind' },
			{ e: '🫀', n: 'anatomical heart', k: 'organ' },
			{ e: '🦷', n: 'tooth', k: 'dentist' },
			{ e: '👀', n: 'eyes', k: 'look watch see' },
			{ e: '👁️', n: 'eye', k: 'look see' },
			{ e: '👅', n: 'tongue', k: 'taste' },
			{ e: '👄', n: 'mouth', k: 'lips kiss' },
			{ e: '👶', n: 'baby', k: 'infant child', t: true },
			{ e: '🧒', n: 'child', k: 'kid', t: true },
			{ e: '👦', n: 'boy', k: 'child', t: true },
			{ e: '👧', n: 'girl', k: 'child', t: true },
			{ e: '🧑', n: 'person', k: 'adult', t: true },
			{ e: '👨', n: 'man', k: 'adult male', t: true },
			{ e: '👩', n: 'woman', k: 'adult female', t: true },
			{ e: '🧓', n: 'older person', k: 'elderly', t: true },
			{ e: '👴', n: 'old man', k: 'grandpa', t: true },
			{ e: '👵', n: 'old woman', k: 'grandma', t: true },
			{ e: '🧑‍💻', n: 'technologist', k: 'developer coder', t: true },
			{ e: '👨‍💻', n: 'man technologist', k: 'developer coder', t: true },
			{ e: '👩‍💻', n: 'woman technologist', k: 'developer coder', t: true },
			{ e: '🧑‍🎨', n: 'artist', k: 'painter designer', t: true },
			{ e: '🧑‍🍳', n: 'cook', k: 'chef', t: true },
			{ e: '🧑‍🏫', n: 'teacher', k: 'professor', t: true },
			{ e: '🧑‍⚕️', n: 'health worker', k: 'doctor nurse', t: true },
			{ e: '🧑‍🚀', n: 'astronaut', k: 'space', t: true },
			{ e: '🕵️', n: 'detective', k: 'spy investigate', t: true },
			{ e: '💂', n: 'guard', k: 'royal', t: true },
			{ e: '👷', n: 'construction worker', k: 'builder', t: true },
			{ e: '🤴', n: 'prince', k: 'royal', t: true },
			{ e: '👸', n: 'princess', k: 'royal', t: true },
			{ e: '🦸', n: 'superhero', k: 'hero', t: true },
			{ e: '🦹', n: 'supervillain', k: 'villain', t: true },
			{ e: '🧙', n: 'mage', k: 'wizard witch', t: true },
			{ e: '🧚', n: 'fairy', k: 'magic', t: true },
			{ e: '🧛', n: 'vampire', k: 'dracula', t: true },
			{ e: '🧜', n: 'merperson', k: 'mermaid', t: true },
			{ e: '🎅', n: 'santa claus', k: 'christmas', t: true },
			{ e: '🤶', n: 'mrs claus', k: 'christmas', t: true },
			{ e: '🙅', n: 'person gesturing no', k: 'stop refuse', t: true },
			{ e: '🙆', n: 'person gesturing ok', k: 'yes', t: true },
			{ e: '💁', n: 'person tipping hand', k: 'info sassy', t: true },
			{ e: '🙋', n: 'person raising hand', k: 'question volunteer', t: true },
			{ e: '🧏', n: 'deaf person', k: 'accessibility', t: true },
			{ e: '🙇', n: 'person bowing', k: 'sorry respect', t: true },
			{ e: '🤦', n: 'person facepalming', k: 'facepalm disbelief', t: true },
			{ e: '🤷', n: 'person shrugging', k: 'shrug idk', t: true },
			{ e: '💆', n: 'person getting massage', k: 'relax spa', t: true },
			{ e: '💇', n: 'person getting haircut', k: 'salon', t: true },
			{ e: '🚶', n: 'person walking', k: 'walk', t: true },
			{ e: '🏃', n: 'person running', k: 'run fast', t: true },
			{ e: '💃', n: 'woman dancing', k: 'dance party', t: true },
			{ e: '🕺', n: 'man dancing', k: 'dance party', t: true },
			{ e: '🧗', n: 'person climbing', k: 'climb', t: true },
			{ e: '🧘', n: 'person in lotus position', k: 'yoga meditate', t: true },
			{ e: '🛀', n: 'person taking bath', k: 'bath relax', t: true },
			{ e: '👪', n: 'family', k: 'parents kids' },
			{ e: '🗣️', n: 'speaking head', k: 'talk say' },
			{ e: '👤', n: 'bust in silhouette', k: 'user person' },
			{ e: '👥', n: 'busts in silhouette', k: 'users group' },
			{ e: '👣', n: 'footprints', k: 'steps' }
		]
	},
	{
		id: 'nature',
		label: 'Animals & Nature',
		emojis: [
			{ e: '🐶', n: 'dog face', k: 'puppy pet' },
			{ e: '🐱', n: 'cat face', k: 'kitten pet' },
			{ e: '🐭', n: 'mouse face', k: 'rodent' },
			{ e: '🐹', n: 'hamster', k: 'pet' },
			{ e: '🐰', n: 'rabbit face', k: 'bunny' },
			{ e: '🦊', n: 'fox', k: 'animal' },
			{ e: '🐻', n: 'bear', k: 'animal' },
			{ e: '🐼', n: 'panda', k: 'bear' },
			{ e: '🐻‍❄️', n: 'polar bear', k: 'arctic' },
			{ e: '🐨', n: 'koala', k: 'australia' },
			{ e: '🐯', n: 'tiger face', k: 'animal' },
			{ e: '🦁', n: 'lion', k: 'king animal' },
			{ e: '🐮', n: 'cow face', k: 'moo' },
			{ e: '🐷', n: 'pig face', k: 'oink' },
			{ e: '🐸', n: 'frog', k: 'toad' },
			{ e: '🐵', n: 'monkey face', k: 'ape' },
			{ e: '🙈', n: 'see no evil monkey', k: 'monkey hide' },
			{ e: '🙉', n: 'hear no evil monkey', k: 'monkey' },
			{ e: '🙊', n: 'speak no evil monkey', k: 'monkey' },
			{ e: '🐒', n: 'monkey', k: 'ape' },
			{ e: '🐔', n: 'chicken', k: 'hen' },
			{ e: '🐧', n: 'penguin', k: 'antarctica' },
			{ e: '🐦', n: 'bird', k: 'tweet' },
			{ e: '🦅', n: 'eagle', k: 'bird' },
			{ e: '🦆', n: 'duck', k: 'bird quack' },
			{ e: '🦉', n: 'owl', k: 'bird night' },
			{ e: '🦇', n: 'bat', k: 'vampire' },
			{ e: '🐺', n: 'wolf', k: 'animal' },
			{ e: '🐗', n: 'boar', k: 'pig' },
			{ e: '🐴', n: 'horse face', k: 'animal' },
			{ e: '🦄', n: 'unicorn', k: 'magic fantasy' },
			{ e: '🐝', n: 'honeybee', k: 'bee bug' },
			{ e: '🪲', n: 'beetle', k: 'bug' },
			{ e: '🐛', n: 'bug', k: 'caterpillar' },
			{ e: '🦋', n: 'butterfly', k: 'insect' },
			{ e: '🐌', n: 'snail', k: 'slow' },
			{ e: '🐞', n: 'lady beetle', k: 'ladybug' },
			{ e: '🐜', n: 'ant', k: 'insect' },
			{ e: '🕷️', n: 'spider', k: 'web' },
			{ e: '🦂', n: 'scorpion', k: 'sting' },
			{ e: '🐢', n: 'turtle', k: 'slow tortoise' },
			{ e: '🐍', n: 'snake', k: 'serpent' },
			{ e: '🦎', n: 'lizard', k: 'reptile' },
			{ e: '🦖', n: 't-rex', k: 'dinosaur' },
			{ e: '🐙', n: 'octopus', k: 'sea' },
			{ e: '🦑', n: 'squid', k: 'sea' },
			{ e: '🦐', n: 'shrimp', k: 'sea' },
			{ e: '🦀', n: 'crab', k: 'sea' },
			{ e: '🐡', n: 'blowfish', k: 'fish' },
			{ e: '🐠', n: 'tropical fish', k: 'fish' },
			{ e: '🐟', n: 'fish', k: 'sea' },
			{ e: '🐬', n: 'dolphin', k: 'sea' },
			{ e: '🐳', n: 'spouting whale', k: 'sea' },
			{ e: '🦈', n: 'shark', k: 'sea jaws' },
			{ e: '🐊', n: 'crocodile', k: 'alligator' },
			{ e: '🐘', n: 'elephant', k: 'animal' },
			{ e: '🦒', n: 'giraffe', k: 'animal' },
			{ e: '🦓', n: 'zebra', k: 'stripes' },
			{ e: '🐎', n: 'horse', k: 'racing' },
			{ e: '🐄', n: 'cow', k: 'cattle' },
			{ e: '🐖', n: 'pig', k: 'farm' },
			{ e: '🐑', n: 'ewe', k: 'sheep' },
			{ e: '🐐', n: 'goat', k: 'farm' },
			{ e: '🦌', n: 'deer', k: 'animal' },
			{ e: '🐕', n: 'dog', k: 'pet' },
			{ e: '🐈', n: 'cat', k: 'pet' },
			{ e: '🪶', n: 'feather', k: 'light bird' },
			{ e: '🐓', n: 'rooster', k: 'cock' },
			{ e: '🦃', n: 'turkey', k: 'thanksgiving' },
			{ e: '🕊️', n: 'dove', k: 'peace bird' },
			{ e: '🐇', n: 'rabbit', k: 'bunny' },
			{ e: '🐁', n: 'mouse', k: 'rodent' },
			{ e: '🦔', n: 'hedgehog', k: 'spiky' },
			{ e: '🌵', n: 'cactus', k: 'desert plant' },
			{ e: '🎄', n: 'christmas tree', k: 'holiday' },
			{ e: '🌲', n: 'evergreen tree', k: 'pine' },
			{ e: '🌳', n: 'deciduous tree', k: 'tree' },
			{ e: '🌴', n: 'palm tree', k: 'beach' },
			{ e: '🪴', n: 'potted plant', k: 'houseplant' },
			{ e: '🌱', n: 'seedling', k: 'sprout grow' },
			{ e: '🌿', n: 'herb', k: 'leaf plant' },
			{ e: '☘️', n: 'shamrock', k: 'clover irish' },
			{ e: '🍀', n: 'four leaf clover', k: 'luck' },
			{ e: '🍃', n: 'leaf fluttering in wind', k: 'leaves' },
			{ e: '🍂', n: 'fallen leaf', k: 'autumn' },
			{ e: '🍁', n: 'maple leaf', k: 'canada autumn' },
			{ e: '🌺', n: 'hibiscus', k: 'flower' },
			{ e: '🌸', n: 'cherry blossom', k: 'flower sakura' },
			{ e: '💐', n: 'bouquet', k: 'flowers' },
			{ e: '🌷', n: 'tulip', k: 'flower' },
			{ e: '🌹', n: 'rose', k: 'flower love' },
			{ e: '🌻', n: 'sunflower', k: 'flower' },
			{ e: '🌼', n: 'blossom', k: 'flower daisy' },
			{ e: '🌾', n: 'sheaf of rice', k: 'grain wheat' },
			{ e: '🍄', n: 'mushroom', k: 'fungi' },
			{ e: '🌍', n: 'globe showing europe africa', k: 'earth world' },
			{ e: '🌎', n: 'globe showing americas', k: 'earth world' },
			{ e: '🌏', n: 'globe showing asia australia', k: 'earth world' },
			{ e: '🌙', n: 'crescent moon', k: 'night' },
			{ e: '🌝', n: 'full moon face', k: 'moon' },
			{ e: '⭐', n: 'star', k: 'favourite' },
			{ e: '🌟', n: 'glowing star', k: 'sparkle' },
			{ e: '✨', n: 'sparkles', k: 'magic shiny new' },
			{ e: '⚡', n: 'high voltage', k: 'lightning fast' },
			{ e: '🔥', n: 'fire', k: 'lit hot flame' },
			{ e: '🌈', n: 'rainbow', k: 'pride colors' },
			{ e: '☀️', n: 'sun', k: 'sunny weather' },
			{ e: '⛅', n: 'sun behind cloud', k: 'weather' },
			{ e: '☁️', n: 'cloud', k: 'weather' },
			{ e: '🌧️', n: 'cloud with rain', k: 'weather rainy' },
			{ e: '⛈️', n: 'cloud with lightning and rain', k: 'storm' },
			{ e: '❄️', n: 'snowflake', k: 'cold winter' },
			{ e: '⛄', n: 'snowman without snow', k: 'winter' },
			{ e: '🌊', n: 'water wave', k: 'ocean sea' },
			{ e: '💧', n: 'droplet', k: 'water drop' },
			{ e: '🌪️', n: 'tornado', k: 'storm' }
		]
	},
	{
		id: 'food',
		label: 'Food & Drink',
		emojis: [
			{ e: '🍏', n: 'green apple', k: 'fruit' },
			{ e: '🍎', n: 'red apple', k: 'fruit' },
			{ e: '🍐', n: 'pear', k: 'fruit' },
			{ e: '🍊', n: 'tangerine', k: 'orange fruit' },
			{ e: '🍋', n: 'lemon', k: 'citrus sour' },
			{ e: '🍌', n: 'banana', k: 'fruit' },
			{ e: '🍉', n: 'watermelon', k: 'fruit summer' },
			{ e: '🍇', n: 'grapes', k: 'fruit wine' },
			{ e: '🍓', n: 'strawberry', k: 'fruit berry' },
			{ e: '🫐', n: 'blueberries', k: 'fruit berry' },
			{ e: '🍈', n: 'melon', k: 'fruit' },
			{ e: '🍒', n: 'cherries', k: 'fruit' },
			{ e: '🍑', n: 'peach', k: 'fruit' },
			{ e: '🥭', n: 'mango', k: 'fruit tropical' },
			{ e: '🍍', n: 'pineapple', k: 'fruit tropical' },
			{ e: '🥥', n: 'coconut', k: 'tropical' },
			{ e: '🥝', n: 'kiwi fruit', k: 'fruit' },
			{ e: '🍅', n: 'tomato', k: 'vegetable' },
			{ e: '🍆', n: 'eggplant', k: 'aubergine' },
			{ e: '🥑', n: 'avocado', k: 'guacamole' },
			{ e: '🥦', n: 'broccoli', k: 'vegetable' },
			{ e: '🥬', n: 'leafy green', k: 'lettuce salad' },
			{ e: '🥒', n: 'cucumber', k: 'pickle' },
			{ e: '🌶️', n: 'hot pepper', k: 'spicy chili' },
			{ e: '🌽', n: 'ear of corn', k: 'maize' },
			{ e: '🥕', n: 'carrot', k: 'vegetable' },
			{ e: '🧄', n: 'garlic', k: 'flavour' },
			{ e: '🧅', n: 'onion', k: 'vegetable' },
			{ e: '🥔', n: 'potato', k: 'vegetable' },
			{ e: '🍠', n: 'roasted sweet potato', k: 'yam' },
			{ e: '🥐', n: 'croissant', k: 'bread french' },
			{ e: '🥯', n: 'bagel', k: 'bread' },
			{ e: '🍞', n: 'bread', k: 'loaf toast' },
			{ e: '🥖', n: 'baguette bread', k: 'french' },
			{ e: '🥨', n: 'pretzel', k: 'snack' },
			{ e: '🧀', n: 'cheese wedge', k: 'dairy' },
			{ e: '🥚', n: 'egg', k: 'breakfast' },
			{ e: '🍳', n: 'cooking', k: 'egg breakfast fry' },
			{ e: '🧈', n: 'butter', k: 'dairy' },
			{ e: '🥞', n: 'pancakes', k: 'breakfast' },
			{ e: '🧇', n: 'waffle', k: 'breakfast' },
			{ e: '🥓', n: 'bacon', k: 'breakfast meat' },
			{ e: '🥩', n: 'cut of meat', k: 'steak' },
			{ e: '🍗', n: 'poultry leg', k: 'chicken drumstick' },
			{ e: '🍖', n: 'meat on bone', k: 'bbq' },
			{ e: '🌭', n: 'hot dog', k: 'sausage' },
			{ e: '🍔', n: 'hamburger', k: 'burger fast food' },
			{ e: '🍟', n: 'french fries', k: 'chips fast food' },
			{ e: '🍕', n: 'pizza', k: 'slice italian' },
			{ e: '🥪', n: 'sandwich', k: 'lunch' },
			{ e: '🌮', n: 'taco', k: 'mexican' },
			{ e: '🌯', n: 'burrito', k: 'mexican wrap' },
			{ e: '🥙', n: 'stuffed flatbread', k: 'kebab' },
			{ e: '🧆', n: 'falafel', k: 'middle eastern' },
			{ e: '🥗', n: 'green salad', k: 'healthy' },
			{ e: '🥘', n: 'shallow pan of food', k: 'paella' },
			{ e: '🍝', n: 'spaghetti', k: 'pasta italian' },
			{ e: '🍜', n: 'steaming bowl', k: 'ramen noodles' },
			{ e: '🍲', n: 'pot of food', k: 'stew soup' },
			{ e: '🍛', n: 'curry rice', k: 'indian' },
			{ e: '🍣', n: 'sushi', k: 'japanese' },
			{ e: '🍱', n: 'bento box', k: 'japanese lunch' },
			{ e: '🥟', n: 'dumpling', k: 'gyoza' },
			{ e: '🍤', n: 'fried shrimp', k: 'tempura' },
			{ e: '🍚', n: 'cooked rice', k: 'bowl' },
			{ e: '🍙', n: 'rice ball', k: 'onigiri' },
			{ e: '🥠', n: 'fortune cookie', k: 'luck' },
			{ e: '🍦', n: 'soft ice cream', k: 'dessert' },
			{ e: '🍧', n: 'shaved ice', k: 'dessert' },
			{ e: '🍨', n: 'ice cream', k: 'dessert' },
			{ e: '🍩', n: 'doughnut', k: 'donut dessert' },
			{ e: '🍪', n: 'cookie', k: 'biscuit dessert' },
			{ e: '🎂', n: 'birthday cake', k: 'celebrate dessert' },
			{ e: '🍰', n: 'shortcake', k: 'cake dessert' },
			{ e: '🧁', n: 'cupcake', k: 'dessert' },
			{ e: '🥧', n: 'pie', k: 'dessert' },
			{ e: '🍫', n: 'chocolate bar', k: 'candy sweet' },
			{ e: '🍬', n: 'candy', k: 'sweet' },
			{ e: '🍭', n: 'lollipop', k: 'candy sweet' },
			{ e: '🍯', n: 'honey pot', k: 'sweet' },
			{ e: '🍿', n: 'popcorn', k: 'movie snack' },
			{ e: '🧂', n: 'salt', k: 'seasoning' },
			{ e: '🥛', n: 'glass of milk', k: 'dairy drink' },
			{ e: '☕', n: 'hot beverage', k: 'coffee tea' },
			{ e: '🫖', n: 'teapot', k: 'tea' },
			{ e: '🍵', n: 'teacup without handle', k: 'green tea' },
			{ e: '🧃', n: 'beverage box', k: 'juice' },
			{ e: '🥤', n: 'cup with straw', k: 'soda drink' },
			{ e: '🧋', n: 'bubble tea', k: 'boba' },
			{ e: '🍺', n: 'beer mug', k: 'drink alcohol' },
			{ e: '🍻', n: 'clinking beer mugs', k: 'cheers' },
			{ e: '🥂', n: 'clinking glasses', k: 'cheers champagne' },
			{ e: '🍷', n: 'wine glass', k: 'drink alcohol' },
			{ e: '🥃', n: 'tumbler glass', k: 'whiskey' },
			{ e: '🍸', n: 'cocktail glass', k: 'martini drink' },
			{ e: '🍹', n: 'tropical drink', k: 'cocktail' },
			{ e: '🍾', n: 'bottle with popping cork', k: 'champagne celebrate' },
			{ e: '🧉', n: 'mate', k: 'drink' },
			{ e: '🍴', n: 'fork and knife', k: 'eat cutlery' },
			{ e: '🍽️', n: 'fork and knife with plate', k: 'dinner eat' },
			{ e: '🥄', n: 'spoon', k: 'cutlery' },
			{ e: '🔪', n: 'kitchen knife', k: 'cut chef' }
		]
	},
	{
		id: 'activity',
		label: 'Activity',
		emojis: [
			{ e: '⚽', n: 'soccer ball', k: 'football sport' },
			{ e: '🏀', n: 'basketball', k: 'sport' },
			{ e: '🏈', n: 'american football', k: 'sport nfl' },
			{ e: '⚾', n: 'baseball', k: 'sport' },
			{ e: '🥎', n: 'softball', k: 'sport' },
			{ e: '🎾', n: 'tennis', k: 'sport' },
			{ e: '🏐', n: 'volleyball', k: 'sport' },
			{ e: '🏉', n: 'rugby football', k: 'sport' },
			{ e: '🥏', n: 'flying disc', k: 'frisbee' },
			{ e: '🎱', n: 'pool 8 ball', k: 'billiards' },
			{ e: '🪀', n: 'yo-yo', k: 'toy' },
			{ e: '🏓', n: 'ping pong', k: 'table tennis' },
			{ e: '🏸', n: 'badminton', k: 'sport' },
			{ e: '🏒', n: 'ice hockey', k: 'sport' },
			{ e: '🥍', n: 'lacrosse', k: 'sport' },
			{ e: '🏏', n: 'cricket game', k: 'sport' },
			{ e: '🥅', n: 'goal net', k: 'sport' },
			{ e: '⛳', n: 'flag in hole', k: 'golf' },
			{ e: '🪁', n: 'kite', k: 'fly wind' },
			{ e: '🏹', n: 'bow and arrow', k: 'archery' },
			{ e: '🎣', n: 'fishing pole', k: 'fish' },
			{ e: '🤿', n: 'diving mask', k: 'snorkel' },
			{ e: '🥊', n: 'boxing glove', k: 'fight sport' },
			{ e: '🥋', n: 'martial arts uniform', k: 'karate judo' },
			{ e: '⛸️', n: 'ice skate', k: 'skating' },
			{ e: '🎿', n: 'skis', k: 'winter sport' },
			{ e: '🛹', n: 'skateboard', k: 'skate' },
			{ e: '🛼', n: 'roller skate', k: 'skating' },
			{ e: '🏋️', n: 'person lifting weights', k: 'gym workout', t: true },
			{ e: '🤸', n: 'person cartwheeling', k: 'gymnastics', t: true },
			{ e: '⛹️', n: 'person bouncing ball', k: 'basketball', t: true },
			{ e: '🤺', n: 'person fencing', k: 'sword sport' },
			{ e: '🤾', n: 'person playing handball', k: 'sport', t: true },
			{ e: '🏌️', n: 'person golfing', k: 'golf', t: true },
			{ e: '🏇', n: 'horse racing', k: 'jockey', t: true },
			{ e: '🧘', n: 'person in lotus position', k: 'yoga meditate', t: true },
			{ e: '🏄', n: 'person surfing', k: 'surf wave', t: true },
			{ e: '🏊', n: 'person swimming', k: 'swim pool', t: true },
			{ e: '🚣', n: 'person rowing boat', k: 'row', t: true },
			{ e: '🚴', n: 'person biking', k: 'cycling bike', t: true },
			{ e: '🚵', n: 'person mountain biking', k: 'cycling', t: true },
			{ e: '🏆', n: 'trophy', k: 'win award champion' },
			{ e: '🥇', n: '1st place medal', k: 'gold win' },
			{ e: '🥈', n: '2nd place medal', k: 'silver' },
			{ e: '🥉', n: '3rd place medal', k: 'bronze' },
			{ e: '🏅', n: 'sports medal', k: 'award' },
			{ e: '🎖️', n: 'military medal', k: 'award honor' },
			{ e: '🎗️', n: 'reminder ribbon', k: 'awareness' },
			{ e: '🎫', n: 'ticket', k: 'event admission' },
			{ e: '🎟️', n: 'admission tickets', k: 'event' },
			{ e: '🎪', n: 'circus tent', k: 'carnival' },
			{ e: '🤹', n: 'person juggling', k: 'juggle circus', t: true },
			{ e: '🎭', n: 'performing arts', k: 'theater drama' },
			{ e: '🎨', n: 'artist palette', k: 'art paint design' },
			{ e: '🎬', n: 'clapper board', k: 'movie film' },
			{ e: '🎤', n: 'microphone', k: 'sing karaoke' },
			{ e: '🎧', n: 'headphone', k: 'music listen' },
			{ e: '🎼', n: 'musical score', k: 'music' },
			{ e: '🎹', n: 'musical keyboard', k: 'piano' },
			{ e: '🥁', n: 'drum', k: 'music' },
			{ e: '🎷', n: 'saxophone', k: 'music jazz' },
			{ e: '🎺', n: 'trumpet', k: 'music' },
			{ e: '🎸', n: 'guitar', k: 'music rock' },
			{ e: '🪕', n: 'banjo', k: 'music' },
			{ e: '🎻', n: 'violin', k: 'music' },
			{ e: '🎲', n: 'game die', k: 'dice random' },
			{ e: '♟️', n: 'chess pawn', k: 'chess game' },
			{ e: '🎯', n: 'bullseye', k: 'target darts goal' },
			{ e: '🎮', n: 'video game', k: 'controller gaming' },
			{ e: '🕹️', n: 'joystick', k: 'arcade gaming' },
			{ e: '🎰', n: 'slot machine', k: 'casino gamble' },
			{ e: '🧩', n: 'puzzle piece', k: 'jigsaw' },
			{ e: '🎉', n: 'party popper', k: 'celebrate congrats' },
			{ e: '🎊', n: 'confetti ball', k: 'celebrate party' },
			{ e: '🎈', n: 'balloon', k: 'party birthday' },
			{ e: '🎁', n: 'wrapped gift', k: 'present birthday' },
			{ e: '🎀', n: 'ribbon', k: 'bow gift' },
			{ e: '🎏', n: 'carp streamer', k: 'japan' },
			{ e: '🎃', n: 'jack-o-lantern', k: 'halloween pumpkin' },
			{ e: '🧨', n: 'firecracker', k: 'explode' },
			{ e: '🎆', n: 'fireworks', k: 'celebrate' },
			{ e: '🎇', n: 'sparkler', k: 'firework' }
		]
	},
	{
		id: 'travel',
		label: 'Travel & Places',
		emojis: [
			{ e: '🚗', n: 'automobile', k: 'car drive' },
			{ e: '🚕', n: 'taxi', k: 'cab' },
			{ e: '🚙', n: 'sport utility vehicle', k: 'suv car' },
			{ e: '🚌', n: 'bus', k: 'transit' },
			{ e: '🚎', n: 'trolleybus', k: 'transit' },
			{ e: '🏎️', n: 'racing car', k: 'f1 fast' },
			{ e: '🚓', n: 'police car', k: 'cop' },
			{ e: '🚑', n: 'ambulance', k: 'emergency' },
			{ e: '🚒', n: 'fire engine', k: 'emergency' },
			{ e: '🚐', n: 'minibus', k: 'van' },
			{ e: '🛻', n: 'pickup truck', k: 'truck' },
			{ e: '🚚', n: 'delivery truck', k: 'shipping' },
			{ e: '🚛', n: 'articulated lorry', k: 'truck' },
			{ e: '🚜', n: 'tractor', k: 'farm' },
			{ e: '🛵', n: 'motor scooter', k: 'vespa' },
			{ e: '🏍️', n: 'motorcycle', k: 'bike' },
			{ e: '🛺', n: 'auto rickshaw', k: 'tuktuk' },
			{ e: '🚲', n: 'bicycle', k: 'bike cycle' },
			{ e: '🛴', n: 'kick scooter', k: 'scooter' },
			{ e: '🚨', n: 'police car light', k: 'siren alert' },
			{ e: '🚔', n: 'oncoming police car', k: 'cop' },
			{ e: '🚍', n: 'oncoming bus', k: 'transit' },
			{ e: '🚅', n: 'bullet train', k: 'shinkansen fast' },
			{ e: '🚄', n: 'high speed train', k: 'rail' },
			{ e: '🚂', n: 'locomotive', k: 'train steam' },
			{ e: '🚇', n: 'metro', k: 'subway underground' },
			{ e: '🚊', n: 'tram', k: 'streetcar' },
			{ e: '🚉', n: 'station', k: 'train' },
			{ e: '✈️', n: 'airplane', k: 'flight travel' },
			{ e: '🛫', n: 'airplane departure', k: 'takeoff' },
			{ e: '🛬', n: 'airplane arrival', k: 'landing' },
			{ e: '🛩️', n: 'small airplane', k: 'flight' },
			{ e: '💺', n: 'seat', k: 'airplane chair' },
			{ e: '🚁', n: 'helicopter', k: 'chopper' },
			{ e: '🚀', n: 'rocket', k: 'launch space ship' },
			{ e: '🛸', n: 'flying saucer', k: 'ufo alien' },
			{ e: '🛰️', n: 'satellite', k: 'space orbit' },
			{ e: '⛵', n: 'sailboat', k: 'boat sailing' },
			{ e: '🛥️', n: 'motor boat', k: 'boat' },
			{ e: '🚤', n: 'speedboat', k: 'boat' },
			{ e: '🛳️', n: 'passenger ship', k: 'cruise' },
			{ e: '🚢', n: 'ship', k: 'boat cargo' },
			{ e: '⚓', n: 'anchor', k: 'ship harbour' },
			{ e: '🚏', n: 'bus stop', k: 'transit' },
			{ e: '🚦', n: 'vertical traffic light', k: 'signal' },
			{ e: '🚧', n: 'construction', k: 'barrier wip' },
			{ e: '⛽', n: 'fuel pump', k: 'gas station' },
			{ e: '🗺️', n: 'world map', k: 'travel atlas' },
			{ e: '🧭', n: 'compass', k: 'navigation direction' },
			{ e: '🗿', n: 'moai', k: 'easter island statue' },
			{ e: '🗽', n: 'statue of liberty', k: 'new york usa' },
			{ e: '🗼', n: 'tokyo tower', k: 'japan' },
			{ e: '🏰', n: 'castle', k: 'fortress' },
			{ e: '🏯', n: 'japanese castle', k: 'japan' },
			{ e: '🏟️', n: 'stadium', k: 'arena' },
			{ e: '🎡', n: 'ferris wheel', k: 'fair' },
			{ e: '🎢', n: 'roller coaster', k: 'theme park' },
			{ e: '🎠', n: 'carousel horse', k: 'fair' },
			{ e: '⛲', n: 'fountain', k: 'water park' },
			{ e: '⛱️', n: 'umbrella on ground', k: 'beach' },
			{ e: '🏖️', n: 'beach with umbrella', k: 'vacation' },
			{ e: '🏝️', n: 'desert island', k: 'tropical' },
			{ e: '🏜️', n: 'desert', k: 'sand' },
			{ e: '🌋', n: 'volcano', k: 'eruption' },
			{ e: '⛰️', n: 'mountain', k: 'hike' },
			{ e: '🏔️', n: 'snow capped mountain', k: 'alps' },
			{ e: '🗻', n: 'mount fuji', k: 'japan' },
			{ e: '🏕️', n: 'camping', k: 'tent outdoors' },
			{ e: '⛺', n: 'tent', k: 'camping' },
			{ e: '🏠', n: 'house', k: 'home' },
			{ e: '🏡', n: 'house with garden', k: 'home' },
			{ e: '🏘️', n: 'houses', k: 'neighbourhood' },
			{ e: '🏢', n: 'office building', k: 'work company' },
			{ e: '🏬', n: 'department store', k: 'shopping' },
			{ e: '🏭', n: 'factory', k: 'industry' },
			{ e: '🏥', n: 'hospital', k: 'medical' },
			{ e: '🏦', n: 'bank', k: 'money' },
			{ e: '🏨', n: 'hotel', k: 'stay' },
			{ e: '🏫', n: 'school', k: 'education' },
			{ e: '⛪', n: 'church', k: 'religion' },
			{ e: '🕌', n: 'mosque', k: 'religion' },
			{ e: '🛕', n: 'hindu temple', k: 'religion' },
			{ e: '🕍', n: 'synagogue', k: 'religion' },
			{ e: '🌆', n: 'cityscape at dusk', k: 'city sunset' },
			{ e: '🌇', n: 'sunset', k: 'city evening' },
			{ e: '🌃', n: 'night with stars', k: 'city night' },
			{ e: '🌉', n: 'bridge at night', k: 'city' },
			{ e: '🌌', n: 'milky way', k: 'space stars' },
			{ e: '🎇', n: 'sparkler', k: 'night' },
			{ e: '🌁', n: 'foggy', k: 'mist city' }
		]
	},
	{
		id: 'objects',
		label: 'Objects',
		emojis: [
			{ e: '⌚', n: 'watch', k: 'time wrist' },
			{ e: '📱', n: 'mobile phone', k: 'smartphone iphone' },
			{ e: '💻', n: 'laptop', k: 'computer macbook' },
			{ e: '⌨️', n: 'keyboard', k: 'typing' },
			{ e: '🖥️', n: 'desktop computer', k: 'monitor pc' },
			{ e: '🖨️', n: 'printer', k: 'print' },
			{ e: '🖱️', n: 'computer mouse', k: 'click' },
			{ e: '💽', n: 'computer disk', k: 'minidisc' },
			{ e: '💾', n: 'floppy disk', k: 'save' },
			{ e: '💿', n: 'optical disk', k: 'cd' },
			{ e: '📀', n: 'dvd', k: 'disc' },
			{ e: '🧮', n: 'abacus', k: 'calculate math' },
			{ e: '🎥', n: 'movie camera', k: 'film' },
			{ e: '📷', n: 'camera', k: 'photo' },
			{ e: '📸', n: 'camera with flash', k: 'photo' },
			{ e: '📹', n: 'video camera', k: 'record' },
			{ e: '📼', n: 'videocassette', k: 'vhs tape' },
			{ e: '🔍', n: 'magnifying glass tilted left', k: 'search find zoom' },
			{ e: '🔎', n: 'magnifying glass tilted right', k: 'search zoom' },
			{ e: '🕯️', n: 'candle', k: 'light' },
			{ e: '💡', n: 'light bulb', k: 'idea' },
			{ e: '🔦', n: 'flashlight', k: 'torch' },
			{ e: '🏮', n: 'red paper lantern', k: 'japan' },
			{ e: '📔', n: 'notebook with decorative cover', k: 'journal' },
			{ e: '📕', n: 'closed book', k: 'read' },
			{ e: '📖', n: 'open book', k: 'read study' },
			{ e: '📚', n: 'books', k: 'library study' },
			{ e: '📓', n: 'notebook', k: 'notes' },
			{ e: '📒', n: 'ledger', k: 'notes' },
			{ e: '📃', n: 'page with curl', k: 'document' },
			{ e: '📜', n: 'scroll', k: 'document ancient' },
			{ e: '📄', n: 'page facing up', k: 'document file' },
			{ e: '📰', n: 'newspaper', k: 'news press' },
			{ e: '🔖', n: 'bookmark', k: 'save tag' },
			{ e: '🏷️', n: 'label', k: 'tag' },
			{ e: '💰', n: 'money bag', k: 'cash rich' },
			{ e: '💴', n: 'yen banknote', k: 'money' },
			{ e: '💵', n: 'dollar banknote', k: 'money cash' },
			{ e: '💳', n: 'credit card', k: 'payment' },
			{ e: '🧾', n: 'receipt', k: 'invoice bill' },
			{ e: '💎', n: 'gem stone', k: 'diamond jewel' },
			{ e: '⚖️', n: 'balance scale', k: 'justice law' },
			{ e: '🪜', n: 'ladder', k: 'climb' },
			{ e: '🧰', n: 'toolbox', k: 'tools' },
			{ e: '🔧', n: 'wrench', k: 'tool fix' },
			{ e: '🔨', n: 'hammer', k: 'tool build' },
			{ e: '⚒️', n: 'hammer and pick', k: 'tools' },
			{ e: '🛠️', n: 'hammer and wrench', k: 'tools settings' },
			{ e: '⛏️', n: 'pick', k: 'mining' },
			{ e: '🔩', n: 'nut and bolt', k: 'hardware' },
			{ e: '⚙️', n: 'gear', k: 'settings cog' },
			{ e: '🧲', n: 'magnet', k: 'attract' },
			{ e: '🔫', n: 'water pistol', k: 'toy gun' },
			{ e: '💣', n: 'bomb', k: 'explode' },
			{ e: '🧪', n: 'test tube', k: 'science lab' },
			{ e: '🧫', n: 'petri dish', k: 'science bacteria' },
			{ e: '🧬', n: 'dna', k: 'genetics science' },
			{ e: '🔬', n: 'microscope', k: 'science lab' },
			{ e: '🔭', n: 'telescope', k: 'space astronomy' },
			{ e: '📡', n: 'satellite antenna', k: 'signal dish' },
			{ e: '💉', n: 'syringe', k: 'vaccine shot' },
			{ e: '💊', n: 'pill', k: 'medicine drug' },
			{ e: '🩹', n: 'adhesive bandage', k: 'plaster fix' },
			{ e: '🩺', n: 'stethoscope', k: 'doctor health' },
			{ e: '🚪', n: 'door', k: 'entrance' },
			{ e: '🪑', n: 'chair', k: 'seat' },
			{ e: '🛏️', n: 'bed', k: 'sleep' },
			{ e: '🛋️', n: 'couch and lamp', k: 'sofa living' },
			{ e: '🚿', n: 'shower', k: 'bath' },
			{ e: '🛁', n: 'bathtub', k: 'bath' },
			{ e: '🧻', n: 'roll of paper', k: 'toilet paper' },
			{ e: '🧼', n: 'soap', k: 'wash clean' },
			{ e: '🧹', n: 'broom', k: 'clean sweep' },
			{ e: '🧺', n: 'basket', k: 'laundry' },
			{ e: '🔑', n: 'key', k: 'unlock access' },
			{ e: '🗝️', n: 'old key', k: 'unlock' },
			{ e: '🔒', n: 'locked', k: 'secure private' },
			{ e: '🔓', n: 'unlocked', k: 'open' },
			{ e: '🔐', n: 'locked with key', k: 'secure' },
			{ e: '🔔', n: 'bell', k: 'notification alert' },
			{ e: '🔕', n: 'bell with slash', k: 'mute silent' },
			{ e: '📣', n: 'megaphone', k: 'announce shout' },
			{ e: '📢', n: 'loudspeaker', k: 'announce' },
			{ e: '📯', n: 'postal horn', k: 'mail' },
			{ e: '📻', n: 'radio', k: 'music broadcast' },
			{ e: '📺', n: 'television', k: 'tv screen' },
			{ e: '☎️', n: 'telephone', k: 'call phone' },
			{ e: '📞', n: 'telephone receiver', k: 'call' },
			{ e: '📟', n: 'pager', k: 'beeper' },
			{ e: '📠', n: 'fax machine', k: 'fax' },
			{ e: '🔋', n: 'battery', k: 'power charge' },
			{ e: '🪫', n: 'low battery', k: 'power' },
			{ e: '🔌', n: 'electric plug', k: 'power' },
			{ e: '✉️', n: 'envelope', k: 'mail email' },
			{ e: '📧', n: 'e-mail', k: 'email mail' },
			{ e: '📨', n: 'incoming envelope', k: 'mail' },
			{ e: '📤', n: 'outbox tray', k: 'send' },
			{ e: '📥', n: 'inbox tray', k: 'receive' },
			{ e: '📦', n: 'package', k: 'box shipping npm' },
			{ e: '📮', n: 'postbox', k: 'mail' },
			{ e: '📝', n: 'memo', k: 'note write edit' },
			{ e: '✏️', n: 'pencil', k: 'write edit' },
			{ e: '🖊️', n: 'pen', k: 'write' },
			{ e: '🖌️', n: 'paintbrush', k: 'art' },
			{ e: '🖍️', n: 'crayon', k: 'draw' },
			{ e: '📐', n: 'triangular ruler', k: 'measure' },
			{ e: '📏', n: 'straight ruler', k: 'measure' },
			{ e: '📌', n: 'pushpin', k: 'pin location' },
			{ e: '📍', n: 'round pushpin', k: 'location pin' },
			{ e: '📎', n: 'paperclip', k: 'attach' },
			{ e: '✂️', n: 'scissors', k: 'cut' },
			{ e: '🗂️', n: 'card index dividers', k: 'files folders' },
			{ e: '📁', n: 'file folder', k: 'directory' },
			{ e: '📂', n: 'open file folder', k: 'directory' },
			{ e: '📅', n: 'calendar', k: 'date schedule' },
			{ e: '📆', n: 'tear off calendar', k: 'date' },
			{ e: '📇', n: 'card index', k: 'contacts' },
			{ e: '📊', n: 'bar chart', k: 'graph stats' },
			{ e: '📈', n: 'chart increasing', k: 'growth up' },
			{ e: '📉', n: 'chart decreasing', k: 'loss down' },
			{ e: '📋', n: 'clipboard', k: 'copy paste list' },
			{ e: '🗒️', n: 'spiral notepad', k: 'notes' },
			{ e: '🗓️', n: 'spiral calendar', k: 'schedule' },
			{ e: '🗑️', n: 'wastebasket', k: 'trash delete bin' },
			{ e: '⏳', n: 'hourglass not done', k: 'time waiting' },
			{ e: '⌛', n: 'hourglass done', k: 'time' },
			{ e: '⏰', n: 'alarm clock', k: 'time wake' },
			{ e: '⏱️', n: 'stopwatch', k: 'timer' },
			{ e: '🕰️', n: 'mantelpiece clock', k: 'time' },
			{ e: '👑', n: 'crown', k: 'king queen royal' },
			{ e: '👓', n: 'glasses', k: 'eyewear' },
			{ e: '🕶️', n: 'sunglasses', k: 'cool shades' },
			{ e: '👔', n: 'necktie', k: 'business' },
			{ e: '👕', n: 'tshirt', k: 'shirt clothes' },
			{ e: '👖', n: 'jeans', k: 'pants' },
			{ e: '👗', n: 'dress', k: 'clothes' },
			{ e: '👞', n: 'mans shoe', k: 'footwear' },
			{ e: '👟', n: 'running shoe', k: 'sneaker' },
			{ e: '🎒', n: 'backpack', k: 'school bag' },
			{ e: '👜', n: 'handbag', k: 'purse' },
			{ e: '🧳', n: 'luggage', k: 'suitcase travel' },
			{ e: '☂️', n: 'umbrella', k: 'rain' },
			{ e: '🧸', n: 'teddy bear', k: 'toy' },
			{ e: '🪞', n: 'mirror', k: 'reflection' },
			{ e: '🛒', n: 'shopping cart', k: 'buy trolley' },
			{ e: '🛍️', n: 'shopping bags', k: 'buy retail' }
		]
	},
	{
		id: 'symbols',
		label: 'Symbols',
		emojis: [
			{ e: '✅', n: 'check mark button', k: 'done yes ok' },
			{ e: '☑️', n: 'check box with check', k: 'done' },
			{ e: '✔️', n: 'check mark', k: 'done yes' },
			{ e: '❌', n: 'cross mark', k: 'no wrong cancel' },
			{ e: '❎', n: 'cross mark button', k: 'no' },
			{ e: '➕', n: 'plus', k: 'add' },
			{ e: '➖', n: 'minus', k: 'subtract' },
			{ e: '➗', n: 'divide', k: 'math' },
			{ e: '✖️', n: 'multiply', k: 'math times' },
			{ e: '🟰', n: 'heavy equals sign', k: 'math' },
			{ e: '♾️', n: 'infinity', k: 'forever' },
			{ e: '‼️', n: 'double exclamation mark', k: 'urgent' },
			{ e: '⁉️', n: 'exclamation question mark', k: 'confused' },
			{ e: '❓', n: 'question mark', k: 'help ask' },
			{ e: '❔', n: 'white question mark', k: 'help' },
			{ e: '❗', n: 'exclamation mark', k: 'warning important' },
			{ e: '⚠️', n: 'warning', k: 'caution alert' },
			{ e: '🚫', n: 'prohibited', k: 'no forbidden' },
			{ e: '⛔', n: 'no entry', k: 'stop' },
			{ e: '🔞', n: 'no one under eighteen', k: 'adult' },
			{ e: '☢️', n: 'radioactive', k: 'nuclear' },
			{ e: '☣️', n: 'biohazard', k: 'danger' },
			{ e: '⬆️', n: 'up arrow', k: 'north' },
			{ e: '↗️', n: 'up right arrow', k: 'northeast' },
			{ e: '➡️', n: 'right arrow', k: 'east next' },
			{ e: '↘️', n: 'down right arrow', k: 'southeast' },
			{ e: '⬇️', n: 'down arrow', k: 'south' },
			{ e: '↙️', n: 'down left arrow', k: 'southwest' },
			{ e: '⬅️', n: 'left arrow', k: 'west back' },
			{ e: '↖️', n: 'up left arrow', k: 'northwest' },
			{ e: '↕️', n: 'up down arrow', k: 'vertical' },
			{ e: '↔️', n: 'left right arrow', k: 'horizontal' },
			{ e: '↩️', n: 'right arrow curving left', k: 'reply back' },
			{ e: '↪️', n: 'left arrow curving right', k: 'forward' },
			{ e: '🔃', n: 'clockwise vertical arrows', k: 'reload sync' },
			{ e: '🔄', n: 'counterclockwise arrows button', k: 'refresh sync' },
			{ e: '🔙', n: 'back arrow', k: 'return' },
			{ e: '🔝', n: 'top arrow', k: 'up' },
			{ e: '🔀', n: 'shuffle tracks button', k: 'random' },
			{ e: '🔁', n: 'repeat button', k: 'loop' },
			{ e: '▶️', n: 'play button', k: 'start' },
			{ e: '⏸️', n: 'pause button', k: 'stop' },
			{ e: '⏹️', n: 'stop button', k: 'end' },
			{ e: '⏺️', n: 'record button', k: 'rec' },
			{ e: '⏭️', n: 'next track button', k: 'skip' },
			{ e: '⏮️', n: 'last track button', k: 'previous' },
			{ e: '🔼', n: 'upwards button', k: 'up' },
			{ e: '🔽', n: 'downwards button', k: 'down' },
			{ e: '🔊', n: 'speaker high volume', k: 'loud audio' },
			{ e: '🔇', n: 'muted speaker', k: 'mute silent' },
			{ e: '♻️', n: 'recycling symbol', k: 'recycle green' },
			{ e: '⚛️', n: 'atom symbol', k: 'science react' },
			{ e: '🔱', n: 'trident emblem', k: 'symbol' },
			{ e: '⚜️', n: 'fleur-de-lis', k: 'symbol' },
			{ e: '🆘', n: 'sos button', k: 'help emergency' },
			{ e: '🆗', n: 'ok button', k: 'okay' },
			{ e: '🆕', n: 'new button', k: 'fresh' },
			{ e: '🆓', n: 'free button', k: 'gratis' },
			{ e: '🔴', n: 'red circle', k: 'dot record' },
			{ e: '🟠', n: 'orange circle', k: 'dot' },
			{ e: '🟡', n: 'yellow circle', k: 'dot' },
			{ e: '🟢', n: 'green circle', k: 'dot online' },
			{ e: '🔵', n: 'blue circle', k: 'dot' },
			{ e: '🟣', n: 'purple circle', k: 'dot' },
			{ e: '⚫', n: 'black circle', k: 'dot' },
			{ e: '⚪', n: 'white circle', k: 'dot' },
			{ e: '🟥', n: 'red square', k: 'block' },
			{ e: '🟧', n: 'orange square', k: 'block' },
			{ e: '🟨', n: 'yellow square', k: 'block' },
			{ e: '🟩', n: 'green square', k: 'block' },
			{ e: '🟦', n: 'blue square', k: 'block' },
			{ e: '🟪', n: 'purple square', k: 'block' },
			{ e: '⬛', n: 'black large square', k: 'block' },
			{ e: '⬜', n: 'white large square', k: 'block' },
			{ e: '🔶', n: 'large orange diamond', k: 'shape' },
			{ e: '🔷', n: 'large blue diamond', k: 'shape' },
			{ e: '🔺', n: 'red triangle pointed up', k: 'shape' },
			{ e: '🔻', n: 'red triangle pointed down', k: 'shape' },
			{ e: '💠', n: 'diamond with a dot', k: 'shape' },
			{ e: '🔘', n: 'radio button', k: 'select' },
			{ e: '🔳', n: 'white square button', k: 'shape' },
			{ e: '⭕', n: 'hollow red circle', k: 'circle no' },
			{ e: '💲', n: 'heavy dollar sign', k: 'money' },
			{ e: '™️', n: 'trade mark', k: 'tm' },
			{ e: '©️', n: 'copyright', k: 'legal' },
			{ e: '®️', n: 'registered', k: 'legal' },
			{ e: '#️⃣', n: 'keycap hash', k: 'hashtag number' },
			{ e: '*️⃣', n: 'keycap asterisk', k: 'star' },
			{ e: '0️⃣', n: 'keycap 0', k: 'zero number' },
			{ e: '1️⃣', n: 'keycap 1', k: 'one number' },
			{ e: '2️⃣', n: 'keycap 2', k: 'two number' },
			{ e: '3️⃣', n: 'keycap 3', k: 'three number' },
			{ e: '4️⃣', n: 'keycap 4', k: 'four number' },
			{ e: '5️⃣', n: 'keycap 5', k: 'five number' },
			{ e: '♠️', n: 'spade suit', k: 'cards' },
			{ e: '♥️', n: 'heart suit', k: 'cards' },
			{ e: '♦️', n: 'diamond suit', k: 'cards' },
			{ e: '♣️', n: 'club suit', k: 'cards' },
			{ e: '🃏', n: 'joker', k: 'cards' },
			{ e: '🀄', n: 'mahjong red dragon', k: 'game' },
			{ e: '☯️', n: 'yin yang', k: 'balance' },
			{ e: '☮️', n: 'peace symbol', k: 'peace' },
			{ e: '✝️', n: 'latin cross', k: 'christian' },
			{ e: '☪️', n: 'star and crescent', k: 'islam' },
			{ e: '🕉️', n: 'om', k: 'hindu' },
			{ e: '✡️', n: 'star of david', k: 'judaism' },
			{ e: '🔯', n: 'dotted six pointed star', k: 'symbol' },
			{ e: '♈', n: 'aries', k: 'zodiac' },
			{ e: '♉', n: 'taurus', k: 'zodiac' },
			{ e: '♊', n: 'gemini', k: 'zodiac' },
			{ e: '♋', n: 'cancer', k: 'zodiac' },
			{ e: '♌', n: 'leo', k: 'zodiac' },
			{ e: '♍', n: 'virgo', k: 'zodiac' },
			{ e: '♎', n: 'libra', k: 'zodiac' },
			{ e: '♏', n: 'scorpio', k: 'zodiac' },
			{ e: '♐', n: 'sagittarius', k: 'zodiac' },
			{ e: '♑', n: 'capricorn', k: 'zodiac' },
			{ e: '♒', n: 'aquarius', k: 'zodiac' },
			{ e: '♓', n: 'pisces', k: 'zodiac' }
		]
	},
	{
		id: 'flags',
		label: 'Flags',
		emojis: [
			{ e: '🏁', n: 'chequered flag', k: 'race finish' },
			{ e: '🚩', n: 'triangular flag', k: 'marker' },
			{ e: '🏳️', n: 'white flag', k: 'surrender' },
			{ e: '🏴', n: 'black flag', k: 'pirate' },
			{ e: '🏳️‍🌈', n: 'rainbow flag', k: 'pride lgbt' },
			{ e: '🏳️‍⚧️', n: 'transgender flag', k: 'pride trans' },
			{ e: '🏴‍☠️', n: 'pirate flag', k: 'jolly roger' },
			{ e: '🇦🇹', n: 'flag austria', k: 'at' },
			{ e: '🇦🇺', n: 'flag australia', k: 'au' },
			{ e: '🇧🇪', n: 'flag belgium', k: 'be' },
			{ e: '🇧🇷', n: 'flag brazil', k: 'br' },
			{ e: '🇨🇦', n: 'flag canada', k: 'ca' },
			{ e: '🇨🇭', n: 'flag switzerland', k: 'ch' },
			{ e: '🇨🇳', n: 'flag china', k: 'cn' },
			{ e: '🇨🇿', n: 'flag czechia', k: 'cz' },
			{ e: '🇩🇪', n: 'flag germany', k: 'de deutschland' },
			{ e: '🇩🇰', n: 'flag denmark', k: 'dk' },
			{ e: '🇪🇸', n: 'flag spain', k: 'es' },
			{ e: '🇪🇺', n: 'flag european union', k: 'eu' },
			{ e: '🇫🇮', n: 'flag finland', k: 'fi' },
			{ e: '🇫🇷', n: 'flag france', k: 'fr' },
			{ e: '🇬🇧', n: 'flag united kingdom', k: 'gb uk britain' },
			{ e: '🇬🇷', n: 'flag greece', k: 'gr' },
			{ e: '🇭🇺', n: 'flag hungary', k: 'hu' },
			{ e: '🇮🇩', n: 'flag indonesia', k: 'id' },
			{ e: '🇮🇪', n: 'flag ireland', k: 'ie' },
			{ e: '🇮🇱', n: 'flag israel', k: 'il' },
			{ e: '🇮🇳', n: 'flag india', k: 'in' },
			{ e: '🇮🇹', n: 'flag italy', k: 'it' },
			{ e: '🇯🇵', n: 'flag japan', k: 'jp' },
			{ e: '🇰🇷', n: 'flag south korea', k: 'kr' },
			{ e: '🇲🇽', n: 'flag mexico', k: 'mx' },
			{ e: '🇳🇱', n: 'flag netherlands', k: 'nl' },
			{ e: '🇳🇴', n: 'flag norway', k: 'no' },
			{ e: '🇳🇿', n: 'flag new zealand', k: 'nz' },
			{ e: '🇵🇱', n: 'flag poland', k: 'pl' },
			{ e: '🇵🇹', n: 'flag portugal', k: 'pt' },
			{ e: '🇷🇴', n: 'flag romania', k: 'ro' },
			{ e: '🇸🇪', n: 'flag sweden', k: 'se' },
			{ e: '🇸🇬', n: 'flag singapore', k: 'sg' },
			{ e: '🇹🇭', n: 'flag thailand', k: 'th' },
			{ e: '🇹🇷', n: 'flag turkey', k: 'tr' },
			{ e: '🇺🇦', n: 'flag ukraine', k: 'ua' },
			{ e: '🇺🇸', n: 'flag united states', k: 'us usa america' },
			{ e: '🇻🇳', n: 'flag vietnam', k: 'vn' },
			{ e: '🇿🇦', n: 'flag south africa', k: 'za' }
		]
	}
];
